#!/bin/bash
clear
[[ $EUID -ne 0 ]] && {
echo -e "\033[1;33mApologize, \033[1;33mYOU MUST USE THE DATABASE SUDO -I TO CALL ROOT.\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo '9:q-7gs1.o1%5:f1.6q5.×9%y4:1'|sed -e 's/[^0-9.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mPLEASE WAIT A MOMENT... \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mPLEASE WAIT A MOMENT... \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
  echo -e "\n\033[1;31mVERIFIED\033[0m"
  rm -rf $HOME/Plus > /dev/null 2>&1
  sleep 2
  clear; exit 1
}
}
echo -e "\033[0;34m══════════════════════════════════════════════════\033[0m"
echo -e "\E[41;1;37m               ⢾ PHCN-VPN MANAGER ⡷                \E[0m"
echo -e "\033[0;34m══════════════════════════════════════════════════\033[0m"
echo ""
echo -e "             \033[1;31mWARNING! \033[1;33mThis SSH OPENVPN SCRIPT!\033[0m"
echo ""
echo -e "\033[1;31m • \033[1;33mINSTALLING SCRIPTS? AS A TOOL\033[0m" 
echo -e "\033[1;33m    FOR SYSTEM NETWORK AND USER MANAGEMENT\033[0m"
echo ""
echo -e "\033[1;32m • \033[1;32mTIPS!\033[1;33mAPPLY A DARK THEME IN YOUR TERMINAL.\033[0m"
echo -e "\033[1;33m    BETTER EXPERIENCE AND VISIBILITY OF THE SAME! \033[0m"
echo ""
echo -e "\033[1;31m««««««««««««««««[\033[1;33m • \033[1;32mBY PECH CHHEAN\033[1;33m •\033[1;31m ]»»»»»»»»»»»»»»»»\033[0m"
echo ""
echo -ne "\033[1;36mINSTALL SCRIPT [N/Y]: \033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
echo -e "\n\033[1;36mCHECKING...\033[1;37mGET\033[0m"
sleep 3s
echo -e "\n\033[1;32mSUCCEED!\033[1;32m"
wget https://github.com/PechScript/solid-engine/raw/WeGo/Autoinstall/list > /dev/null 2>&1
chmod +x list ./list > /dev/null 2>&1
sleep 1s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
    clear
    echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo ""
	echo -e "                 \033[1;33m• \033[1;31mWARNING \033[1;33m• \033[0m"
	echo ""
    echo -e "\033[1;33m USER DATABASE \033[1;32m(usuarios.db) \033[1;33mIS" 
    echo -e "  I HAVE IT! YOU WANT TO USE THIS CURRENT INFORMATION, RIGHT?"
	echo -e "  CURRENT USER ACCOUNT? OR YOU WANT"
    ech echo -e "  CREATE A NEW DATABASE?\033[0m"

	echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mUSE THIS CURRENT DATABASE\033[0m"
	echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCREATE A NEW DATABASE\033[0m"
	echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo ""
	tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 optiondb ; tput sgr0
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' " WAIT FOR INSTALLATION..." ; tput sgr0
echo ""
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mUPDATING THE SYSTEM \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
echo ""
echo -e "    \033[1;33m  UPDATING THE SUN CAN TAKE A LONG TIME!\033[0m"
echo ""
fun_attlist () {
    apt-get update -y
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALLING PACKAGES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33m  SOME PACKAGES ARE EXTREMELY IMPORTANT!\033[0m"
echo ""
inst_pct () {
apt-get install bc -y > /dev/null 2>&1
apt-get install screen -y > /dev/null 2>&1
apt-get install nano -y > /dev/null 2>&1
apt-get install unzip -y > /dev/null 2>&1
apt-get install lsof -y > /dev/null 2>&1
apt-get install netstat -y > /dev/null 2>&1
apt-get install net-tools -y > /dev/null 2>&1
apt-get install dos2unix -y > /dev/null 2>&1
apt-get install nload -y > /dev/null 2>&1
apt-get install jq -y > /dev/null 2>&1
apt-get install curl -y > /dev/null 2>&1
apt-get install figlet -y > /dev/null 2>&1
apt-get install python3 -y > /dev/null 2>&1
apt-get install python-pip -y > /dev/null 2>&1
pip install speedtest-cli > /dev/null 2>&1
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 8181/tcp ; ufw allow 3128/tcp ; ufw allow 8686/tcp ; ufw allow 8000/tcp ;ufw allow 9090/tcp
clear
echo ""
echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mPLEASE DO NOT CLOSE THIS WINDOW. \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "      \033[1;33m INSTALLING OTHER FUNCTIONS AND BATTLES! \033[0m"
echo ""
fun_bar "source list"
rm Plus* > /dev/null 2>&1
rm list* > /dev/null 2>&1
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
wget https://raw.githubusercontent.com/teamvpn/SSHPLUS24/master/versao > /dev/null 2>&1
clear
echo ""
cd $HOME
echo -e "        \033[1;33m • \033[1;32mTHE INSTALLATION IS COMPLETE.\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mOPEN THE COMMAND: \033[1;32mmenu\033[0m"
echo -e "\033[1;33mCONTACT US\033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@PechChhean\033[0m"
rm -rf $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
